
#########################################################
# Makefile
#########################################################

GIT_ROOT 	?= $(shell git rev-parse --show-toplevel)

SOPC_DIR 	?= $(GIT_ROOT)/fpga/de2/src
SOPC	    ?= de2

include $(GIT_ROOT)/demo/scripts/makefile.intel.mk
