# TCL File Generated by Component Editor 13.0sp1
# Mon Jun 13 15:48:47 PDT 2022
# DO NOT MODIFY


# 
# avalon_sram_controller "Avalon MM Sram Controller" v1.0
# Heqing Huang 2022.06.13.15:48:47
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module avalon_sram_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_sram_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Memories and Memory Controllers/External Memory Interfaces/Memory Interfaces"
set_module_property AUTHOR "Heqing Huang"
set_module_property DISPLAY_NAME "Avalon MM Sram Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_sram_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_sram_controller.sv SYSTEM_VERILOG PATH avalon_sram_controller.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter AVN_AW INTEGER 19 "Address width"
set_parameter_property AVN_AW DEFAULT_VALUE 19
set_parameter_property AVN_AW DISPLAY_NAME AVN_AW
set_parameter_property AVN_AW TYPE INTEGER
set_parameter_property AVN_AW UNITS None
set_parameter_property AVN_AW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AVN_AW DESCRIPTION "Address width"
set_parameter_property AVN_AW HDL_PARAMETER true
add_parameter AVN_DW INTEGER 16 "Data width"
set_parameter_property AVN_DW DEFAULT_VALUE 16
set_parameter_property AVN_DW DISPLAY_NAME AVN_DW
set_parameter_property AVN_DW TYPE INTEGER
set_parameter_property AVN_DW UNITS None
set_parameter_property AVN_DW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AVN_DW DESCRIPTION "Data width"
set_parameter_property AVN_DW HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point sram
# 
add_interface sram conduit end
set_interface_property sram associatedClock ""
set_interface_property sram associatedReset ""
set_interface_property sram ENABLED true
set_interface_property sram EXPORT_OF ""
set_interface_property sram PORT_NAME_MAP ""
set_interface_property sram SVD_ADDRESS_GROUP ""

add_interface_port sram sram_we_n export Output 1
add_interface_port sram sram_be_n export Output AVN_DW/8
add_interface_port sram sram_addr export Output AVN_AW
add_interface_port sram sram_dq export Bidir AVN_DW
add_interface_port sram sram_oe_n export Output 1
add_interface_port sram sram_ce_n export Output 1


# 
# connection point avn
# 
add_interface avn avalon end
set_interface_property avn addressUnits WORDS
set_interface_property avn associatedClock clock
set_interface_property avn associatedReset reset
set_interface_property avn bitsPerSymbol 8
set_interface_property avn burstOnBurstBoundariesOnly true
set_interface_property avn burstcountUnits WORDS
set_interface_property avn explicitAddressSpan 0
set_interface_property avn holdTime 0
set_interface_property avn isMemoryDevice true
set_interface_property avn linewrapBursts false
set_interface_property avn maximumPendingReadTransactions 1
set_interface_property avn readLatency 0
set_interface_property avn readWaitStates 0
set_interface_property avn readWaitTime 0
set_interface_property avn setupTime 0
set_interface_property avn timingUnits Cycles
set_interface_property avn writeWaitTime 0
set_interface_property avn ENABLED true
set_interface_property avn EXPORT_OF ""
set_interface_property avn PORT_NAME_MAP ""
set_interface_property avn SVD_ADDRESS_GROUP ""

add_interface_port avn avn_readdatavalid readdatavalid Output 1
add_interface_port avn avn_byteenable byteenable Input AVN_DW/8
add_interface_port avn avn_readdata readdata Output AVN_DW
add_interface_port avn avn_writedata writedata Input AVN_DW
add_interface_port avn avn_address address Input AVN_AW
add_interface_port avn avn_write write Input 1
add_interface_port avn avn_read read Input 1
set_interface_assignment avn embeddedsw.configuration.isFlash 0
set_interface_assignment avn embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment avn embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avn embeddedsw.configuration.isPrintableDevice 0

